// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA29clPfXKlYRzZTRWYkbU4t1VGKgJoqHo',
    appId: '1:934632517143:web:dcf9f457c5efbc3393f652',
    messagingSenderId: '934632517143',
    projectId: 'culture-map-app',
    authDomain: 'culture-map-app.firebaseapp.com',
    storageBucket: 'culture-map-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEfw1VA2eK_jFFZ9bJwerZc5wTIH8EsU',
    appId: '1:934632517143:android:0e9e0beb9a80808793f652',
    messagingSenderId: '934632517143',
    projectId: 'culture-map-app',
    storageBucket: 'culture-map-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGj47ohW3-28BMxmAUuEE4XshZYg-cl9Q',
    appId: '1:934632517143:ios:f2b53e3cc682f5e393f652',
    messagingSenderId: '934632517143',
    projectId: 'culture-map-app',
    storageBucket: 'culture-map-app.firebasestorage.app',
    iosBundleId: 'com.example.culturemap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGj47ohW3-28BMxmAUuEE4XshZYg-cl9Q',
    appId: '1:934632517143:ios:f2b53e3cc682f5e393f652',
    messagingSenderId: '934632517143',
    projectId: 'culture-map-app',
    storageBucket: 'culture-map-app.firebasestorage.app',
    iosBundleId: 'com.example.culturemap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA29clPfXKlYRzZTRWYkbU4t1VGKgJoqHo',
    appId: '1:934632517143:web:44faa5afb0d83f7d93f652',
    messagingSenderId: '934632517143',
    projectId: 'culture-map-app',
    authDomain: 'culture-map-app.firebaseapp.com',
    storageBucket: 'culture-map-app.firebasestorage.app',
  );
}
